# Agregar su credenciales de mongo atlas

spring:
  data:
    mongodb:
      database: db_ms_movements
      uri: mongodb+srv://jhianpol:12345@cluster0.hvzkv.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
server:
  port: 8085
